# Generated by Django 4.1.4 on 2023-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('caracteristica_empresa', models.TextField()),
            ],
        ),
    ]
